apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf-converter.fullname" . }}
  namespace: {{ template "pdf-converter.namespace" . }}
  labels:
    {{- include "pdf-converter.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdf-converter
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pdf-converter.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: pdf-converter