apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdf-converter.fullname" . }}
  namespace: {{ template "pdf-converter.namespace" . }}
  labels:
    {{- include "pdf-converter.labels" . | nindent 4 }}
    app.kubernetes.io/component: pdf-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pdf-converter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pdf-converter
  {{- with .Values.deploymentStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pdf-converter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: pdf-converter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pdf-converter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pdf-converter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: storage-volume
              mountPath: /app/storage
          env:
            - name: STORAGE_DIR
              value: "/app/storage"
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: {{ include "pdf-converter.pvc" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}